# Generated by Django 6.0.3 on 2026-03-22 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(choices=[('low', 'Бюджетно (до 500 ₽)'), ('medium', 'Средний (500–1500 ₽)'), ('high', 'Выше среднего (1500–3000 ₽)'), ('any', 'Не важно, главное — атмосфера')], max_length=20)),
                ('atmosphere', models.CharField(choices=[('party', 'Шумно и тусовочно'), ('cozy', 'Уютно и камерно'), ('romantic', 'Романтично'), ('tasty', 'Не важно, главное — чтобы вкусно')], max_length=20)),
                ('purpose', models.CharField(choices=[('coffee', 'Кофе и завтраки'), ('lunch', 'Обеды и ужины'), ('bars', 'Бары и вечеринки'), ('walks', 'Прогулки и необычные места'), ('all', 'Всё сразу')], max_length=20)),
                ('company_type', models.CharField(choices=[('friends', 'С друзьями'), ('partner', 'С партнёром'), ('alone', 'Один/одна'), ('group', 'С компанией (4+ человек)')], max_length=20)),
                ('distance', models.CharField(choices=[('5_10', '5–10 минут пешком'), ('15_20', '15–20 минут пешком'), ('transport', 'Готов/а доехать пару остановок'), ('any', 'Не важно')], max_length=20)),
                ('extra_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
