# Generated by Django 6.0.3 on 2026-03-22 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('coffee', 'Кофе и завтраки'), ('food', 'Обеды и ужины'), ('bar', 'Бары и вечеринки'), ('walk', 'Прогулки и необычные места'), ('music', 'Живая музыка'), ('other', 'Другое')], default='other', max_length=30)),
                ('short_description', models.CharField(max_length=300)),
                ('full_description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('metro', models.CharField(blank=True, max_length=100)),
                ('average_check', models.PositiveIntegerField(blank=True, null=True)),
                ('atmosphere', models.CharField(choices=[('party', 'Шумно и тусовочно'), ('cozy', 'Уютно и камерно'), ('romantic', 'Романтично'), ('tasty', 'Главное — вкусно'), ('work', 'Подходит для работы'), ('other', 'Другое')], default='other', max_length=30)),
                ('tags_text', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Добавлено вручную'), ('import', 'Импорт'), ('yandex_api', 'Yandex API')], default='manual', max_length=30)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_places', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='places', to='places.placetag')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('external_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
